system:
  #EMBY 域名 包含http(s)和端口号后面不带/
  #例如https://xxx.xxx.xxx:8920
  embyhost: ''
  #EMBY 用户ID 进EMBY 用户点击管理员账号配置可以在网址上看到userId
  embyuserid: ''
  #EMBY APIKEY
  embykey: ''
  #TMDB APIKEY
  tmdbkey: ''
  #豆瓣 APIKEY
  doubankey: '0ac44ae016490db2204ce0a042db2916'
  #线程数量 豆瓣API有请求频率限制建议线程数量不要过多
  threadnum: 1
  #是否刷新人名
  updatepeople: True
  #是否更新概述
  updateoverview: True
  #每次刷新全部媒体间隔时间 [小时]
  updatetime: 1
  #任务完成等待时间 [秒] 豆瓣API有请求频率限制建议时间可以设置长一点
  taskdonespace: 1
  #删除没有头像的演员 强迫症患者福音
  delnotimagepeople: True